name: CloudMap
channels:
  - conda-forge
  - defaults
dependencies:
  - backports=1.0
  - backports.functools_lru_cache=1.5
  - backports_abc=0.5
  - basemap=1.2.0
  - basemap-data-hires=1.2.0
  - blas=1.0
  - boost-cpp=1.68.0
  - bzip2=1.0.6
  - ca-certificates=2019.3.9
  - certifi=2019.3.9
  - curl=7.64.0
  - cycler=0.10.0
  - expat=2.2.5
  - freetype=2.10.0
  - freexl=1.0.5
  - functools32=3.2.3.2
  - futures=3.2.0
  - gdal=2.2.2
  - geos=3.6.2
  - geotiff=1.4.2
  - hdf4=4.2.13
  - hdf5=1.10.1
  - icu=58.2
  - intel-openmp=2019.3
  - jpeg=9c
  - kealib=1.4.8
  - kiwisolver=1.0.1
  - krb5=1.16.3
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.64.0
  - libffi=3.2.1
  - libgdal=2.2.2
  - libiconv=1.15
  - libkml=1.3.0
  - liblapack=3.8.0
  - libnetcdf=4.4.1.1
  - libpng=1.6.36
  - libpq=10.6
  - libspatialite=4.3.0a
  - libssh2=1.8.0
  - libtiff=4.0.10
  - libxml2=2.9.8
  - matplotlib=2.2.3
  - matplotlib-base=2.2.3
  - mkl=2019.1
  - numpy=1.13.3
  - olefile=0.46
  - openjpeg=2.3.0
  - openssl=1.0.2r
  - pandas=0.24.2
  - pcre=8.41
  - pillow=6.0.0
  - pip=19.0.3
  - poppler-data=0.4.9
  - postgresql=10.6
  - proj4=4.9.3
  - pyparsing=2.3.1
  - pyproj=1.9.5.1
  - pyqt=5.6.0
  - pyserial=2.7
  - pyshp=2.1.0
  - python=2.7.15
  - python-dateutil=2.8.0
  - pytz=2018.9
  - qt=5.6.2
  - setuptools=40.8.0
  - singledispatch=3.4.0.3
  - sip=4.18.1
  - six=1.12.0
  - sqlite=3.26.0
  - tk=8.6.9
  - tornado=5.1.1
  - wheel=0.33.1
  - xerces-c=3.2.2
  - xlrd=1.1.0
  - xz=5.2.4
  - zlib=1.2.11
