name: EE5_testing
channels:
  - conda-forge
  - defaults
dependencies:
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.5=py_1
  - backports_abc=0.5=py_1
  - basemap=1.2.0=py27hbee0394_0
  - blas=1.0=mkl
  - boost-cpp=1.68.0=h099cdad_1000
  - bzip2=1.0.6=h0c8e037_1002
  - ca-certificates=2019.3.9=hecc5488_0
  - certifi=2019.3.9=py27_0
  - curl=7.64.0=h2f83ebf_2
  - cycler=0.10.0=py_1
  - expat=2.2.5=h2880e7c_1002
  - freetype=2.10.0=hd7a5a12_0
  - freexl=1.0.5=haa51a25_1002
  - functools32=3.2.3.2=py_3
  - futures=3.2.0=py27_1000
  - gdal=2.2.2=py27h58389d3_1
  - geos=3.6.2=h2880e7c_3
  - geotiff=1.4.2=hd8d3b67_1005
  - hdf4=4.2.13=ha32470c_1002
  - hdf5=1.10.1=vc9_2
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=vc9_0
  - intel-openmp=2019.3=203
  - jpeg=9c=h0c8e037_1001
  - kealib=1.4.8=hc56fc5f_0
  - kiwisolver=1.0.1=py27hdc96acc_1002
  - krb5=1.16.3=hb4d044e_1000
  - libblas=3.8.0=4_mkl
  - libcblas=3.8.0=4_mkl
  - libcurl=7.64.0=h2f83ebf_2
  - libffi=3.2.1=hc56fc5f_1006
  - libgdal=2.2.2=h75964b3_1
  - libiconv=1.15=h0c8e037_1005
  - libkml=1.3.0=ha00ce3f_1009
  - liblapack=3.8.0=4_mkl
  - libnetcdf=4.4.1.1=vc9_10
  - libpng=1.6.36=h7a46e7a_1000
  - libpq=10.6=h35af135_1000
  - libspatialite=4.3.0a=he01c9b4_1023
  - libssh2=1.8.0=h0990ea7_1003
  - libtiff=4.0.10=he490001_1001
  - libxml2=2.9.8=h00b1425_1005
  - m2w64-expat=2.1.1=2
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gettext=0.19.7=2
  - m2w64-gmp=6.1.0=2
  - m2w64-libiconv=1.14=6
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - m2w64-xz=5.2.2=2
  - matplotlib=2.2.3=py27h8a2030e_1
  - matplotlib-base=2.2.3=py27hf194043_1
  - mkl=2019.1=144
  - msys2-conda-epoch=20160418=1
  - numpy=1.13.3=py27hda5cba4_3
  - openjpeg=2.3.0=h73d032e_1003
  - openssl=1.0.2r=h0c8e037_0
  - pandas=0.24.2=py27hc56fc5f_0
  - pcre=8.41=hc56fc5f_1003
  - pip=19.0.3=py27_0
  - poppler-data=0.4.9=1
  - postgresql=10.6=h5f81938_1000
  - proj4=4.9.3=h0c8e037_8
  - pyparsing=2.3.1=py_0
  - pyproj=1.9.5.1=py27he834874_1006
  - pyqt=5.6.0=py27h4cbc711_1008
  - pyshp=2.1.0=py_0
  - python=2.7.15=h2880e7c_1008
  - python-dateutil=2.8.0=py_0
  - pytz=2018.9=py_0
  - qt=5.6.2=vc9_1
  - setuptools=40.8.0=py27_0
  - singledispatch=3.4.0.3=py27_1000
  - sip=4.18.1=py27hc56fc5f_1000
  - six=1.12.0=py27_1000
  - sqlite=3.26.0=h0c8e037_1001
  - tk=8.6.9=h0c8e037_1000
  - tornado=5.1.1=py27h0c8e037_1000
  - vc=9=0
  - vs2008_runtime=9.0.30729.6161=0
  - vs2015_runtime=14.15.26706=h3a45250_0
  - wheel=0.33.1=py27_0
  - wincertstore=0.2=py27_1002
  - xerces-c=3.2.2=hc56fc5f_1001
  - xlrd=1.1.0=py_2
  - xz=5.2.4=h3cc03e0_1001
  - zlib=1.2.11=h3cc03e0_1004
prefix: C:\ProgramData\Anaconda3\envs\EE5_testing

